debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.example.boardservice: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: sc
    # TODO: eventually use environment var to set password
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  h2.console.enabled: true
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
  # option exposed via ThymeleafConfig.Thymeleaf3Properties
  # IDE-level documentation and autocomplete enabled via configuration-processor package
  thymeleaf3:
    decoupled-logic: true


---

# configures the H2 database to run in-memory, and in mysql compatibility mode
# add annotation @ActiveProfiles("testdb") to class JpaRepositoryTest to use this
# JPA automatically spins up its own test db
# add @AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
#   to prevent it from spinning up its test db
spring:
  config:
    activate:
      on-profile: testdb
  datasource:
    url: jdbc:h2:mem:board;mode=mysql
    driver-class-name: org.h2.Driver
  sql.init.mode: always
  # uncomment next line to globally replace JPA's test db
  # test.database.replace: none

